apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_name }}
spec:
  selector:
    app:  {{ .Values.selector_name }}
  ports:
  - port: {{ .Values.port_no }}
    protocol: TCP
    targetPort: {{ .Values.target_port }}
